project:
  type: website
  output-dir: ../docs 
  resources: 
    - ../reports/figs/
    - ../videos/
    - ../screenshots/
    - ../videos/
    - ../images/

website:
  title: "DSAN 6650 Final Project"
  favicon: "../images/gu-logo.png"
  navbar:
    right:
      - href: introduction.qmd
        text: Introduction
      - href: environment.qmd
        text: Environment
      - href: methods.qmd
        text: Methods 
      - href: results.qmd
        text: Results
      - href: analysis.qmd
        text: Analysis
      - href: conclusion.qmd
        text: Conclusion
      - href: references.qmd
        text: References
      - icon: github
        href: "https://github.com/courtneyrgreen/dsan6650-final-project.github.io.git"
format:
  html:
    theme: lumen
    css: styles.css
    page-layout: full
    toc: true
    toc-depth: 3


